### ISSUE TITLE
Wront url in plugin page

### ISSUE THREAD

**Issue by linonetwo** [NodeBB/nodebb-plugin-hashtags#240]
https://github.com/NodeBB/nodebb-plugin-hashtags/blob/baf6b535eddad0cb49b03b9a937768bd2b86aad5/package.json#L8

causes this link to be wrong

<img width="653" alt="截屏2023-10-13 13 37 23" src="https://github.com/NodeBB/nodebb-plugin-hashtags/assets/3746270/d9651915-3a87-46b9-bc47-ec5f8ce1e170">

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-plugin-hashtags/blob/master/package.json
